# Site Settings
baseurl: ""
url : "https://pennyblack2008.github.io"

# Blog Settings
theme_settings :
  title : 산책 좋아하는 개발자 PennyBlack
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/pbluckjikang2.jpeg
    username : PennyBlack2008
    description : 산책 좋아하는 개발자. 컴공 개그 좋아합니다. 유쾌한 것들을 개발하고 있습니다. 동료들과 재밌게 일합니다.
    experience :
      - start : 2020-01-03
        end : 2022-02-23
        experience : 42, Cadet
    skills :
      - skill : C
        value : 85  # Percent value
      - skill : JS, TS
        value : 75  # Percent value
      - skill : C++
        value : 45  # Percent value
      - skill : React
        value : 45  # Percent value

  # Icons
  icons :
    email: g2ang12@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin: https://www.linkedin.com/in/jinwoo-kang-568726154/ # Full URL
    github: PennyBlack2008
    gitlab:
    bitbucket:
    google_plus:
    twitter: jikangDoinWeird
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
